require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FlashMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # FlashMessage. As you add validations to FlashMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tvplay" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FlashMessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all flash_messages as @flash_messages" do
      flash_message = FlashMessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:flash_messages).should eq([flash_message])
    end
  end

  describe "GET show" do
    it "assigns the requested flash_message as @flash_message" do
      flash_message = FlashMessage.create! valid_attributes
      get :show, {:id => flash_message.to_param}, valid_session
      assigns(:flash_message).should eq(flash_message)
    end
  end

  describe "GET new" do
    it "assigns a new flash_message as @flash_message" do
      get :new, {}, valid_session
      assigns(:flash_message).should be_a_new(FlashMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested flash_message as @flash_message" do
      flash_message = FlashMessage.create! valid_attributes
      get :edit, {:id => flash_message.to_param}, valid_session
      assigns(:flash_message).should eq(flash_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FlashMessage" do
        expect {
          post :create, {:flash_message => valid_attributes}, valid_session
        }.to change(FlashMessage, :count).by(1)
      end

      it "assigns a newly created flash_message as @flash_message" do
        post :create, {:flash_message => valid_attributes}, valid_session
        assigns(:flash_message).should be_a(FlashMessage)
        assigns(:flash_message).should be_persisted
      end

      it "redirects to the created flash_message" do
        post :create, {:flash_message => valid_attributes}, valid_session
        response.should redirect_to(FlashMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved flash_message as @flash_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        FlashMessage.any_instance.stub(:save).and_return(false)
        post :create, {:flash_message => { "tvplay" => "invalid value" }}, valid_session
        assigns(:flash_message).should be_a_new(FlashMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FlashMessage.any_instance.stub(:save).and_return(false)
        post :create, {:flash_message => { "tvplay" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested flash_message" do
        flash_message = FlashMessage.create! valid_attributes
        # Assuming there are no other flash_messages in the database, this
        # specifies that the FlashMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FlashMessage.any_instance.should_receive(:update).with({ "tvplay" => "MyString" })
        put :update, {:id => flash_message.to_param, :flash_message => { "tvplay" => "MyString" }}, valid_session
      end

      it "assigns the requested flash_message as @flash_message" do
        flash_message = FlashMessage.create! valid_attributes
        put :update, {:id => flash_message.to_param, :flash_message => valid_attributes}, valid_session
        assigns(:flash_message).should eq(flash_message)
      end

      it "redirects to the flash_message" do
        flash_message = FlashMessage.create! valid_attributes
        put :update, {:id => flash_message.to_param, :flash_message => valid_attributes}, valid_session
        response.should redirect_to(flash_message)
      end
    end

    describe "with invalid params" do
      it "assigns the flash_message as @flash_message" do
        flash_message = FlashMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FlashMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => flash_message.to_param, :flash_message => { "tvplay" => "invalid value" }}, valid_session
        assigns(:flash_message).should eq(flash_message)
      end

      it "re-renders the 'edit' template" do
        flash_message = FlashMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FlashMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => flash_message.to_param, :flash_message => { "tvplay" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested flash_message" do
      flash_message = FlashMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => flash_message.to_param}, valid_session
      }.to change(FlashMessage, :count).by(-1)
    end

    it "redirects to the flash_messages list" do
      flash_message = FlashMessage.create! valid_attributes
      delete :destroy, {:id => flash_message.to_param}, valid_session
      response.should redirect_to(flash_messages_url)
    end
  end

end
